name: Check for compilation failures

on: [push, pull_request]

jobs:
  build:
    name: Check for compilation failures
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install git build-essential autoconf nasm curl mtools -y

      - name: Build the bootloader
        run: ./autogen.sh && make all
