name: Check for compilation failures

on: [push, pull_request]

jobs:
  build:
    name: Check for compilation failures
    runs-on: ubuntu-latest
    container: alpine:edge

    steps:
      - name: Upgrade container
        run: apk update && apk upgrade

      - name: Install dependencies
        run: apk add build-base git autoconf automake nasm mtools llvm clang lld

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build the bootloader (LLVM)
        run: ./bootstrap && ./configure CROSS_TOOLCHAIN=llvm --enable-werror --enable-all && make all && make maintainer-clean

      - name: Build the bootloader (GCC)
        run: ./bootstrap && ./configure CROSS_CC=gcc CROSS_LD=ld CROSS_OBJCOPY=objcopy CROSS_OBJDUMP=objdump CROSS_READELF=readelf --enable-werror --enable-all && make all && make maintainer-clean
